name: Continuous Integration (CI)

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build and Package
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v2
            with:
                java-version: "11"
                distribution: "adopt"
          - name: Build with Maven
            run: mvn clean package -DskipTests
    test:
        name: Unit, integration and e2e tests
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            
          - name: Set up JDK 11
            uses: actions/setup-java@v2
            with:
                java-version: "11"
                distribution: "adopt"
          - name: Install Google Chrome and ChromeDriver to e2e tests
            run: |
                sudo apt-get update
                sudo apt-get install -y google-chrome-stable
                CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
                curl -L -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
                unzip chromedriver.zip
                chmod +x chromedriver
                sudo mv chromedriver /usr/local/bin/
          - name: Run application to e2e tests
            run: mvn spring-boot:run -Ptest & sleep 60
          - name: Run tests
            run: mvn clean verify -Ptest
    qa:
        name: Quality Assurance with Sonarqube
        needs: test
        runs-on: self-hosted
        continue-on-error: true
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v2
            with:
                java-version: "11"
                distribution: "adopt"
          - name: Build with Maven skipping tests and with test profile
            run: mvn clean package -DskipTests
          - name: Sonarqube scan
            run: |
                mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -
                Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin
    deploy:
        name: Deploy Application in Azure
        runs-on: ubuntu-latest
        needs: qa
        steps:
          - name: Deploy
            run: echo "Deploy Application in Azure"
